### ISSUE TITLE
Support buildout pickedversions

### ISSUE THREAD

**Issue by jaap3** [rocketDuck/folivora#2]
I'm using buildout and the buildout.dumppickedversions extension. This generates a file with the exact versions each time the project is built.

A versions file looks like this:

```
[versions]
PackageName = 1.0.0
package = 2.1.2
foo = 0.1.3
bar = 1.4.2
baz = 2.1.1
etc = 0.7.5
```

**Comment by EnTeQuAk** [comment]
Requires #7 to be fixed so that we can create a perfect matching as buildout normalizes keys with ConfigParser so that a matching is not that easy.

**Comment by EnTeQuAk** [comment]
#7 and #12 were fixed so I close this as well.
