### ISSUE TITLE
Allow for find-links

### ISSUE THREAD

**Issue by jaap3** [rocketDuck/folivora#3]
My projects use a fair amount of private packages hosted on a private pypi server, it would be great if find-links were supported.

http://guide.python-distribute.org/pip.html#add-urls-to-search-for-links

**Comment by EnTeQuAk** [comment]
@jaap3 if you say "private pypi server" you probably mean that it is stored somewhere on a private network, right? Or do you also use some authentication to connect to it?

**Comment by jaap3** [comment]
It's private by way of IP filtering. So in order for folivora to check it for updates the folivora IP has to be whitelisted on the private cheeseshop. Otherwise it works just like a normal pypi server.

**Comment by EnTeQuAk** [comment]
Side note: This also requires that the remote pypi server implements all XML-RPC interfaces. We need to verify that during the setup-step in order to support a smooth workflow for the end user
